name: xecurecode
resource_group: Resourcegrp1
location: canadacentral
language: python
runtime: python:3.9

env:
  FLASK_ENV: production
  FLASK_APP: wsgi.py
  WEBSITES_PORT: 8000
  SCM_DO_BUILD_DURING_DEPLOYMENT: 1
  PYTHON_PATH: /home/site/wwwroot
  PYTHONPATH: /home/site/wwwroot
  PYTHON_ENABLE_LOGGING: 1

build:
  commands:
    - python -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - mkdir -p logs data uploads
    - chmod 755 logs data uploads

startup_command: gunicorn --bind=0.0.0.0:8000 --timeout 600 --workers 4 --log-level debug wsgi:application

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 