name: xecurecode
language: python
startCommand: gunicorn wsgi:app
runtime: python:3.9

env:
  FLASK_ENV: production
  FLASK_APP: wsgi.py
  WEBSITES_PORT: 8000
  SCM_DO_BUILD_DURING_DEPLOYMENT: true
  POST_BUILD_COMMAND: pip install -r requirements.txt

build:
  commands:
    - pip install --upgrade pip
    - pip install -r requirements.txt

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 