name: xecurecode
language: python
startCommand: gunicorn --bind=0.0.0.0 --timeout 600 wsgi:app
runtime: python|3.9

env:
  FLASK_ENV: production
  FLASK_APP: wsgi.py
  WEBSITES_PORT: 8000

build:
  commands:
    - pip install -r requirements.txt

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 