name: xecurecode
language: python
runtime: python:3.9

env:
  FLASK_ENV: production
  FLASK_APP: wsgi.py
  WEBSITES_PORT: 8000
  SCM_DO_BUILD_DURING_DEPLOYMENT: true
  PYTHON_PATH: /home/site/wwwroot
  STARTUP_COMMAND: python -m gunicorn wsgi:app --bind=0.0.0.0:8000

build:
  commands:
    - pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - chmod +x startup.sh

post_build:
  commands:
    - mkdir -p /home/site/wwwroot/logs
    - mkdir -p /home/site/wwwroot/data
    - mkdir -p /home/site/wwwroot/uploads

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 