name: xecurecode
resource_group: Resourcegrp1
location: canadacentral
app_service_plan: achal.b.bansal_asp_7884
language: python
runtime: python:3.9

env:
  FLASK_ENV: production
  FLASK_APP: wsgi.py
  WEBSITES_PORT: 8000
  SCM_DO_BUILD_DURING_DEPLOYMENT: 1
  PYTHON_PATH: /home/site/wwwroot
  PYTHONPATH: /home/site/wwwroot
  PYTHON_ENABLE_LOGGING: 1
  WEBSITES_CONTAINER_START_TIME_LIMIT: 1800
  POST_BUILD_COMMAND: pip install -r requirements.txt

pre_build:
  commands:
    - apt-get update
    - apt-get install -y libzbar0

build:
  commands:
    - python -m pip install --upgrade pip setuptools wheel
    - pip install --no-cache-dir -r requirements.txt
    - mkdir -p /home/site/wwwroot/logs
    - mkdir -p /home/site/wwwroot/data
    - mkdir -p /home/site/wwwroot/uploads
    - chmod 755 /home/site/wwwroot/logs
    - chmod 755 /home/site/wwwroot/data
    - chmod 755 /home/site/wwwroot/uploads

post_build:
  commands:
    - python -m compileall .

startup_command: >-
  gunicorn
  --bind=0.0.0.0:8000
  --timeout 600
  --workers 4
  --access-logfile /home/site/wwwroot/logs/access.log
  --error-logfile /home/site/wwwroot/logs/error.log
  --log-level debug
  --capture-output
  wsgi:application

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 