name: xecurecode
language: python
runtime: python:3.9

env:
  FLASK_ENV: production
  FLASK_APP: application.py
  WEBSITES_PORT: 8000
  SCM_DO_BUILD_DURING_DEPLOYMENT: 1
  PYTHON_PATH: /home/site/wwwroot
  STARTUP_FILE: application.py

build:
  commands:
    - python -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt

post_deploy:
  commands:
    - mkdir -p /home/site/wwwroot/logs
    - mkdir -p /home/site/wwwroot/data
    - mkdir -p /home/site/wwwroot/uploads
    - chmod +x startup.sh

routes:
  - route: /
    rewrite: /
  - route: /static/*
    rewrite: /static/{0}
  - route: /uploads/*
    rewrite: /uploads/{0} 